version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  tests:
    jobs:
      - python/test:
          test-tool: pytest
          matrix:
            parameters:
              version: ["3.6", "3.8", "3.9"]
