version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  tests:
    jobs:
      - python/test:
          pre-steps:
            - run:
                name: Install HTML Tidy
                command: |
                  wget https://github.com/htacg/tidy-html5/releases/download/5.8.0/tidy-5.8.0-Linux-64bit.deb && sudo dpkg -i tidy-5.8.0-Linux-64bit.deb
                  rm tidy-5.8.0-Linux-64bit.deb

          test-tool: pytest
          matrix:
            parameters:
              version: ["3.6", "3.8", "3.9", "4.0"]
              args: ["&& pip install django==3.2"]
          post-steps:
            - run: 
                command: |
                  black . --check
                  python manage.py check